### ISSUE TITLE
customize batman colors

### ISSUE THREAD

**Issue by gigibytes** [eth-p/bat-extras#104]
hi there. how can i customize the colors used by batman? the man page for it is sparse so not sure if there's some way to do this. are the colors hardcoded?

**Comment by eth-p** [comment]
The colors are based on the `bat` theme, which you can set with the `BAT_THEME` environment variable. A full list of themes is available by running `bat --list-themes`. Unfortunately, it seems that most of themes lack highlighting for flags, though.

<img width="865" alt="image" src="https://github.com/eth-p/bat-extras/assets/32112321/7fa465ef-0d24-4457-8d0c-cb515835f384">

**Comment by gigibytes** [comment]
Fantastic, thanks. Will see if I can figure out getting flags highlighted for the themes that lack it.
