### ISSUE TITLE
batgrep with rga (ripgrep-all)

### ISSUE THREAD

**Issue by pacien** [eth-p/bat-extras#111]
`rga` ([ripgrep-all]) is a wrapper for ripgrep which can also search in PDF,
office documents, ebooks, archives, …

[ripgrep-all]: https://github.com/phiresky/ripgrep-all

How can I have `batgrep` use `rga` instead of `rg`?

(Using the former as alternate executable seems to break the tests).

**Comment by eth-p** [comment]
I haven't heard of `ripgrep-all` before, but I'll see what I can do after I'm done with finals. As long as the command line isn't drastically different from regular ripgrep, I should be able to add support for it.

**Comment by eth-p** [comment]
Added in https://github.com/eth-p/bat-extras/commit/5011f0709ed51480962c0a350e00bba2637009d8 as the `--rga` flag. It will be fully available in the next release, but you can build `batgrep` from master in the meantime.

There isn't a built-in way to specify that you always want to use `ripgrep-all`, but a shell alias should help:

```bash
alias batgrep='batgrep --rga'
```

**Comment by eth-p** [comment]
Added in [v2024.02.12](https://github.com/eth-p/bat-extras/releases/tag/v2024.02.12).
