### ISSUE TITLE
Install instructions for Debian/Aptitude 

### ISSUE THREAD

**Issue by p1r473** [eth-p/bat-extras#116]
Hey!
I couldnt find any install instructions for Debian/Aptitude so I whipped up 
`for file in /home/pi/bat-extras/src/*.sh; do cp "$file" "/usr/local/bin/$(basename "${file%.sh}")" && chmod +x "/usr/local/bin/$(basename "${file%.sh}")"; done` if you want to list this in the README

**Comment by eth-p** [comment]
I'm somewhat surprised that works, to be honest. The files you copied to `/usr/local/bin` include files from under the `lib` directory [at runtime](https://github.com/eth-p/bat-extras/blob/75c757817fe974d22f4143a55c94a4174342d88d/src/batman.sh#L11-L17), and it wouldn't be able to find those library scripts if they were copied.

The intended approach to installing `bat-extras` would be to either symlink those files to `/usr/local/bin`, or use the `build.sh` script to create standalone scripts.

**Comment by p1r473** [comment]
@eth-p can you please me point to the documentation that I can use the proper way?

**Comment by eth-p** [comment]
The [installation section](https://github.com/eth-p/bat-extras?tab=readme-ov-file#installation) in the README covers how to install `bat-extras` on distros that don't have it as a package. `./build.sh --install --prefix=$HOME/.local` will package the commands into self-contained shell scripts and add them to `~/.local/bin`.

**Comment by p1r473** [comment]
Thanks!
