### ISSUE TITLE
Install through Homebrew

### ISSUE THREAD

**Issue by christopher-francisco** [eth-p/bat-extras#12]
I can help, just let me know if this is ok

**Comment by hahuang65** [comment]
Following, looking forward to this.

**Comment by eth-p** [comment]
I would absolutely love to get these scripts added to homebrew, and I definitely could use some help navigating the process to get this added to the homebrew core tap.

Is there any kind of release process I would have to follow, or any kind of restrictions with compiled artifacts?

**Comment by hahuang65** [comment]
@eth-p I haven't personally worked with adding Homebrew formulae, but this seems to be the good starting point: https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md

**Comment by eth-p** [comment]
Based on their [acceptable formulae documentation](https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Formulae.md), I don't think `bat-extras` currently meets the criteria to have something added to the main Homebrew core tap. Specifically, the following:

- "be known"
- "We frown on authors submitting their own work unless it is very popular."

In the meantime, I [created a tap](https://github.com/eth-p/homebrew-software) that should cover `bat-extras`.

**Comment by eth-p** [comment]
It's been a few months, and I think the custom tap has served its purpose of solving this.

I'm going to close this issue now, but please feel free to reopen it if you have any questions or objections.
