### ISSUE TITLE
Prettybat does not prettifies minified json 

### ISSUE THREAD

**Issue by Demianeen** [eth-p/bat-extras#125]
When I wanted to look prettified json, I used to use:
```bash
prettier --parser json < ./minified.json | bat -l json
```

So, I was curious to try prettybat that should do this in half the characters written. So, I have tried:
```bash
prettybat ./minified.json
```

But the json file was still minified:
![CleanShot 2024-08-16 at 09 52 12@2x](https://github.com/user-attachments/assets/23132a87-3a9f-4f3d-a9fb-5f6bfde26864)

I also haven't found any option in prettybat --help. 

Can I somehow prettify minified json with prettybat?

**Comment by eth-p** [comment]
Fixed in https://github.com/eth-p/bat-extras/commit/47cfb9ec7341728e94e2bb90a892df23461cc8ea, using `yq` as the formatter instead of `prettier`.

**Comment by Demianeen** [comment]
I am using nix, so I can have a depracated version. I am not near the pc for now, so I will just close it for now and reopen if any issue arises. Thanks @eth-p!
