### ISSUE TITLE
batwatch syntax error

### ISSUE THREAD

**Issue by hahuang65** [eth-p/bat-extras#13]
It seems that using `batwatch` on any file with a timestamp results in a syntax problem:

```bash
$ batwatch /var/log/pacman.log
/usr/bin/batwatch: line 449: [[: 2020-03-23 11:20:33.584328650 -0700: syntax error in expression (error token is "11:20:33.584328650 -0700")
```

**Comment by eth-p** [comment]
I'm not currently able to reproduce this. Are you able to provide a sample file?

**Comment by hahuang65** [comment]
Feel free to close this issue. I don't currently have a file I can send you, and I'm not planning to use `batwatch` for the foreseeable future.

Thanks for checking in though, really appreciate your work on all the tools!
