### ISSUE TITLE
Failed to dynamically evaluate a conditional operator.

### ISSUE THREAD

**Issue by VeryTastyTomato** [eth-p/bat-extras#14]
https://github.com/eth-p/bat-extras/blob/6b57f3ff3c6c94f89181c97b64f53b0295f84bb6/lib/version.sh#L51

This raises a syntax error. I don’t think it’s possible to store an operator as a string in a variable and then “apply” it dynamically (or maybe with something like `eval()`?).

**Comment by eth-p** [comment]
That's weird. It should work without any issues...

`[` (but not `[[`) is usually a regular executable inside /bin (or functionally-equivalent shell built-in. The operator and operands provided are just regular string arguments, and should be able to be expanded from variables.

Can I have a bit more info so I can reproduce it? 

What operating system?  
What version of Bash are you using, and what builtins are enabled? 
Are you using the standalone scripts with minification?

**Comment by VeryTastyTomato** [comment]
Nevermind, it’s a bug in the checker I use, and when I investigated it I did it wrongly. Sorry for the noise.
