### ISSUE TITLE
MacOS: batgrep tests fail

### ISSUE THREAD

**Issue by mouse07410** [eth-p/bat-extras#17]
MacOS Catalina 10.15.4, bash. bat-0.13.0. Current master of this repo.

```
$ ./test.sh 
--------------------------------------------------------------------------------------------
| Test Suite: batgrep                                                                      |
--------------------------------------------------------------------------------------------
[FAIL] option_context       :: Exited with code 2.
[FAIL] output_with_color    :: Exited with code 2.
[FAIL] output_without_color :: Exited with code 2.
[FAIL] regular_file         :: Exited with code 2.
[FAIL] search_fixed         :: Exited with code 2.
[FAIL] search_regex         :: Exited with code 2.
[FAIL] symlink_file         :: Exited with code 2.

Totals:
    PASS: 0 / 7
    FAIL: 7 / 7
--------------------------------------------------------------------------------------------
| Test Suite: lib_opt                                                                      |
--------------------------------------------------------------------------------------------
[PASS] long                 :: 20 ms
[PASS] long_value_explicit  :: 20 ms
[PASS] long_value_implicit  :: 25 ms
[PASS] short_value_explicit :: 28 ms
[PASS] short_value_implicit :: 21 ms

Totals:
    PASS: 5 / 5
    FAIL: 0 / 5

ALL TESTS PASSED.
--------------------------------------------------------------------------------------------
| Test Suite: lib_version                                                                  |
--------------------------------------------------------------------------------------------
[PASS] compare_eq           :: 22 ms
[PASS] compare_ge           :: 23 ms
[PASS] compare_gt           :: 27 ms
[PASS] compare_le           :: 27 ms
[PASS] compare_lt           :: 25 ms
[PASS] compare_ne           :: 28 ms

Totals:
    PASS: 6 / 6
    FAIL: 0 / 6

ALL TESTS PASSED.
```

**Comment by eth-p** [comment]
That's odd. Could you please run the tests with the `--verbose` flag and paste the output for me?

**Comment by mouse07410** [comment]
```sh
$ ./test.sh --verbose
--------------------------------------------------------------------------------------------
| Test Suite: batgrep                                                                      |
--------------------------------------------------------------------------------------------
[FAIL] option_context       :: Exited with code 2.
 .... STDERR:
 .... |    1 /Users/ur20980/src/bat-extras/src/batgrep.sh: line 194: rg: command not found
[FAIL] output_with_color    :: Exited with code 2.
 .... STDERR:
 .... |    1 /Users/ur20980/src/bat-extras/src/batgrep.sh: line 194: rg: command not found
[FAIL] output_without_color :: Exited with code 2.
 .... STDERR:
 .... |    1 /Users/ur20980/src/bat-extras/src/batgrep.sh: line 194: rg: command not found
[FAIL] regular_file         :: Exited with code 2.
 .... STDERR:
 .... |    1 /Users/ur20980/src/bat-extras/src/batgrep.sh: line 194: rg: command not found
[FAIL] search_fixed         :: Exited with code 2.
 .... STDERR:
 .... |    1 /Users/ur20980/src/bat-extras/src/batgrep.sh: line 194: rg: command not found
[FAIL] search_regex         :: Exited with code 2.
 .... STDERR:
 .... |    1 /Users/ur20980/src/bat-extras/src/batgrep.sh: line 194: rg: command not found
[FAIL] symlink_file         :: Exited with code 2.
 .... STDERR:
 .... |    1 /Users/ur20980/src/bat-extras/src/batgrep.sh: line 194: rg: command not found

Totals:
    PASS: 0 / 7
    FAIL: 7 / 7
--------------------------------------------------------------------------------------------
| Test Suite: lib_opt                                                                      |
--------------------------------------------------------------------------------------------
[PASS] long                 :: 20 ms
[PASS] long_value_explicit  :: 19 ms
[PASS] long_value_implicit  :: 21 ms
[PASS] short_value_explicit :: 27 ms
[PASS] short_value_implicit :: 23 ms

Totals:
    PASS: 5 / 5
    FAIL: 0 / 5

ALL TESTS PASSED.
--------------------------------------------------------------------------------------------
| Test Suite: lib_version                                                                  |
--------------------------------------------------------------------------------------------
[PASS] compare_eq           :: 21 ms
[PASS] compare_ge           :: 27 ms
[PASS] compare_gt           :: 30 ms
[PASS] compare_le           :: 26 ms
[PASS] compare_lt           :: 30 ms
[PASS] compare_ne           :: 22 ms

Totals:
    PASS: 6 / 6
    FAIL: 0 / 6

ALL TESTS PASSED.
$ 
```

**Comment by eth-p** [comment]
Is there any chance that you don't have ripgrep (`rg`) installed, or have it installed under a different binary name?

**Comment by mouse07410** [comment]
> s there any chance that you don't have `ripgrep` installed?

100%. What README mentioned/told to install it, what build script checked for it?

After installing it (via Macports), all tests are passing:
![Screen Shot 2020-04-06 at 09 46 47](https://user-images.githubusercontent.com/5923577/78565194-8b852480-77eb-11ea-957e-e06234060b26.png)

**Suggested action:** since some people (myself included) have no clue what `ripgrep` is, whether it's included in the `bat-extras` installation automatically or not - say in the README what extra functionality `ripgrep` would add, and that the user needs to install it himself if he wants it.

**Comment by eth-p** [comment]
I partially remedied this with b72a495de1fc46089f9fd60b1f465f5567a7f437, which changed the tests to skip `batgrep` tests unless ripgrep was installed.

Following your suggestions, I'm definitely going to be improving the README and documentation to mention prerequisite programs as well.

**Comment by mouse07410** [comment]
> changed the tests to skip batgrep tests unless `ripgrep` was installed

I do not like this approach. It's probably worse than failing - at least the failure alerted me to bring the issue up here, and as a result - address it by installing `ripgrep`. Your way, I wouldn't even know that there's a problem, because the tests would just avoid pointing at it. Not good!

> I'm definitely going to be improving the README and documentation to mention prerequisite programs as well

Thank you! Listing the pre-reqs, and maybe even what they'd do (i.e., why I may want to have `ripgrep` installed, and what good would `batgrep` do) will make users' lives much easier, IMHO.

**Comment by eth-p** [comment]
> I do not like this approach. It's probably worse than failing - at least the failure alerted me to bring the issue up here, and as a result - address it by installing `ripgrep`. Your way, I wouldn't even know that there's a problem, because the tests would just avoid pointing at it. Not good!

I can see what you mean with that, but it isn't nearly as bad as it sounds. When you check it with `./test.sh` it makes it clear that the test was skipped along with a message explaining why. In the `build.sh` script, it warns you any tests are skipped, and in the CI it treats skipped tests as errors. It would be relatively easy to change it from skipped tests into failing tests though, if that's the more ideal way to handle it.


> Thank you! Listing the pre-reqs, and maybe even what they'd do (i.e., why I may want to have `ripgrep` installed, and what good would `batgrep` do) will make users' lives much easier, IMHO.

I wrote some simple descriptions and added them to the README and the docs for the individual scripts. There's still a lot of room for improvement, but it should help explain what the scripts actually do.

**Comment by mouse07410** [comment]
Thank you!
