### ISSUE TITLE
batgrep: "no pattern provided"

### ISSUE THREAD

**Issue by sharkdp** [eth-p/bat-extras#2]
I can't seem to get `batgrep` to work correctly, as I always get this error message:
```
▶ bin/batgrep foo
batgrep: no pattern provided
```

My bash version is
```
GNU bash, Version 5.0.7(1)-release (x86_64-pc-linux-gnu)
```

I am using `bat` 0.12.1 and `ripgrep` 0.10.0

**Comment by eth-p** [comment]
I can confirm that this happens with Bash 5.x, but not on 3.2 (the macOS default).
I'll look into it and see what's going on.

**Comment by eth-p** [comment]
It seems that the behaviour of `$BASH_ARGV` has changed somewhere between Bash 3.2 and Bash 5. On 3.2, it would contain the arguments for the script itself, but on 5 it seems to either not exist, or simply contains the arguments for the function instead (which would be empty in the function I used it in).

**Comment by eth-p** [comment]
It should be fixed in https://github.com/eth-p/bat-extras/commit/5749d9ea2d6bcabec5b3f529b0df9c1382026c06, but I'll keep this issue open until you're also able to confirm that it works on your system.

**Comment by sharkdp** [comment]
Works great, thank you!

Really like how the `batgrep` output looks like :+1:
