### ISSUE TITLE
./build.sh prints all output to stderr except for the smfmt warning

### ISSUE THREAD

**Issue by lilyball** [eth-p/bat-extras#29]
If I run `./build.sh 2>/dev/null` the only output I get is

```
> ./build.sh 2>/dev/null
Warning: cannot find shfmt. Unable to minify scripts.
>
```

This seems rather backwards; I'd have expected the warning to go to stderr and everything else to go to stdout.

**Comment by eth-p** [comment]
Thanks for reporting. Fixed!

**Comment by eth-p** [comment]
Ah, sorry. That might be a bit trickier to fix, since I'm using STDOUT to pipe data to each different step as part of build process. I'll see what I can do, though.

**Comment by eth-p** [comment]
Nevermind, that was actually pretty simple. `exec 3>&1` saved the day. Fixed in 840d339c971ced316566f9d7d0a1dcf7eae65368

**Comment by lilyball** [comment]
Thanks! This is very nearly correct, except the tests are still using stderr, which looks odd when I run `./build.sh >/dev/null`. I see each test name printed with no context, and then when it finishes the final test is left intact.

It looks to me as though it's printing tests on stderr because if the test fails it wants that to go to stderr. In this case it should print the test to stderr if it failed, otherwise print to stdout.

**Comment by eth-p** [comment]
I tried to fix it in 43ddb984f5911026c432bae48c8903bd0882abab, but I'm not too sure how well it will hold up. On one hand, if you `1>/dev/null`, it should show the failing tests in stderr now.  On the other hand, using `2>/dev/null` would have hid the reason why the build failed. I used a little a couple more ANSI escape sequences, and it tries to print to both stdout and stderr now.

**Comment by lilyball** [comment]
Here I was thinking that you could move the initial `printc_err "\x1B[G\x1B[K%s" "$data1"` into the `case`, because you're printing this after each test has run, not before, so we already know what the result was and can just direct it into the appropriate bucket from the get-go. Something like

```bash
	while read -r action data1 data2 splat; do
		[[ "$action" == "result" ]] || continue

		case "$data2" in
			fail)
				printc_err "\x1B[G\x1B[K%s failed.\n" "$data1"
				((FAIL++)) || true
				;;

			skip)
				printc_msg "\x1B[G\x1B[K%s" "$data1"
				((SKIP++)) || true
				;;

			*)
				printc_msg "\x1B[G\x1B[K%s" "$data1"
				;;
		esac
	done < <("${HERE}/test.sh" --compiled --porcelain --jobs=8)
```

**Comment by eth-p** [comment]
Perfect! Pushed the changes in 5fbf8adf41f68cd9a69fe6a2c8df969fe020d2bd.

**Comment by lilyball** [comment]
Looks great. Thanks!
