### ISSUE TITLE
batman: two-finger scrolling does not work on macOS

### ISSUE THREAD

**Issue by sumanthratna** [eth-p/bat-extras#32]
the following commands allow two-finger scrolling:
- `man vim`
- `vimtutor`
- `nano`

`batman vim` does not allow two-finger scrolling, but keyboard scrolling works.

I'm on macOS 10.15.5 Beta, using Terminal.app.

**Comment by eth-p** [comment]
What version of `less` are you using? The `batman` command lets `bat` handle paging, and `bat` will pass `--no-init` (which prevents mouse scrolling) unless `less --version >= 530`.

https://github.com/sharkdp/bat/blob/master/src/output.rs#L92-L102

**Comment by sumanthratna** [comment]
Thanks for your reply! `less --version` shows:
```
less 487 (POSIX regular expressions)
Copyright (C) 1984-2016  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Homepage: http://www.greenwoodsoftware.com/less
```
I'll close this.

**Comment by sumanthratna** [comment]
Sorry to bump this, but can you explain what the bug with `--quit-if-one-screen` is?

https://github.com/sharkdp/bat/blob/48a7ce3bf23edee81274e6448cf98288ec6f7d31/src/output.rs#L85-L102

It might be nice to allow users to choose whether to sacrifice mouse scrolling or `--quit-if-one-screen`. If you think this is a reasonable request, I'll create a new issue in [sharkdp/bat](https://github.com/sharkdp/bat).

**Comment by sharkdp** [comment]
you can already do this. add `--pager="less --whatever --options"` to `bat`s config file (https://github.com/sharkdp/bat#configuration-file)

**Comment by sumanthratna** [comment]
Sorry to bump an old thread. I've figured out that `bat longfile --pager "less -R"` works for files that don't fit in the terminal, and `bat shortfile --pager "less -R -F --no-init --quit-if-one-screen"` works for files that do fit in the terminal. It seems like an if-statement (see https://unix.stackexchange.com/questions/107315/less-quit-if-one-screen-without-no-init) should let me add the appropriate arguments. However, I don't think I can use this control flow in a bat config file since I need the file path. 

I could create an alias/function, but it looks like that won't work with bat-extras. 
https://github.com/eth-p/bat-extras/blob/6052d6ee1766606bb5647579ea4e02f907919f3d/src/batman.sh#L38

Let me know if I should create a new issue in the main repo.

**Comment by eth-p** [comment]
Apologizies about not replying to your question about the bug. My notification emails get buried sometimes, unfortunately.

 When less initializes (without `--no-init`) the terminal for displaying contents, it enters the VT100 alternate screen mode. This mode has its own screen buffer, which is cleared after exiting the alternate screen. Prior to the patch, less would enter and immediately exit alternate screen mode when `--quit-if-one-screen` is provided and the content is small enough to fit in one screen. That makes the content disappear before the user can see it, which gives the appearance of it not working in the first place.

---

As for conditionally toggling between the options:

You could use a wrapper script (executable file with a shebang), and that should work with bat-extras. As long as bat-extras finds that first in the PATH, it will use it.

More ideally though, if you can update less to a version that has the bug fixed, everything should work without the need for any of that.
