### ISSUE TITLE
batgrep: short options unrecognized when combined with value (ex: -C3)

### ISSUE THREAD

**Issue by jonathanpoelen** [eth-p/bat-extras#34]
`./src/batgrep.sh -C2 a banner.txt`: batgrep: unknown option '-C2'
`./src/batgrep.sh -C 2 a banner.txt`: ok

**Comment by eth-p** [comment]
The command line argument parser isn't suited too well for this, but I'll see what I can do.

**Comment by eth-p** [comment]
Fixed in df5b237273f6e5bfb04d91d243d33be3d59be09a.

**Comment by eth-p** [comment]
@jonathanpoelen Has the fix worked for you? I would like to close this if possible.

**Comment by jonathanpoelen** [comment]
Yes it's good
