### ISSUE TITLE
batgrep will not output, line 198 "rg"

### ISSUE THREAD

**Issue by ContactLeft** [eth-p/bat-extras#38]
user:~/ $ grep                                                                                                                                                                       [11:54:16]
[batgrep error]: no pattern provided
user:~/ $ ls | grep test                                                                                                                                                             [11:54:18]
/usr/local/bin/batgrep.sh: line 198: rg: command not found
user:~/ $ ps -aux | grep bat                                                                                                                                                         [11:54:27]
/usr/local/bin/batgrep.sh: line 198: rg: command not found
user:~/ $

**Comment by eth-p** [comment]
Do you have ripgrep installed? Batgrep uses ripgrep for searching through the list of files.

Additionally, the syntax is as follows:

```bash
# batgrep PATTERN file file ...
batgrep "[0-9]+" log.txt
```

**Comment by ContactLeft** [comment]
thats solved it, thank you very much.
