### ISSUE TITLE
doc/prettybat.md: Caveats section seems to be out of date

### ISSUE THREAD

**Issue by ssokolow** [eth-p/bat-extras#39]
> The header displayed by bat will show `STDIN` instead of the filename.

This no longer appears to be true in my tests, and there *is* a `PRINT_ARGS+=("--file-name" "$1")` line in `prettybat.sh`.

(I didn't open a PR because, for all I know, I just haven't tested it thoroughly enough to catch the problem situation.)

**Comment by eth-p** [comment]
Thanks for pointing that out. Updated in 0494e41e6635f24e234ee444ded2bc0c9b7abf8d.
