### ISSUE TITLE
Build option to specify the bat executable name/path.

### ISSUE THREAD

**Issue by eth-p** [eth-p/bat-extras#4]
Some systems might not have `bat` as the default name for the bat executable.
The name is already used by a different package in Debian, and the bat executable will be [renamed](https://github.com/sharkdp/bat/issues/656) in the upstream Debian package repository.

An option to specify the name/path of the bat executable should be added to the build script.

**Comment by paride** [comment]
Thanks @eth-p. I hope there is a reasonably clean/easy way to achieve this, so the same changes will allow to parameterize `fd` too.

**Comment by eth-p** [comment]
I don't really expect this repo (scripts for integrating bat with other tools) to have an effect on the build system for bat or fd, but I'll definitely be seeing what I can do to help out on the bat repo!

**Comment by eth-p** [comment]
Fixed in 3d4a0b8381fc424c4a5f1eb8182557cf1eb34c1d.
