### ISSUE TITLE
Does batman.sh script handle more syntax that man with bat as manpager?

### ISSUE THREAD

**Issue by pvonmoradi** [eth-p/bat-extras#49]
In bat's readme, there are 2 ways to use bat as man's manpager:  https://github.com/sharkdp/bat#man  

I see [here](https://github.com/eth-p/bat-extras/blob/165fc69d3475927d4ed653dceed432be5b62f8c2/src/batman.sh#L11-L16) that batman script includes a couple of constants from a lib dir. But I didn't notice any difference in viewing gcc,gdb,fprintf manpages.  

Can you explain whether `batman.sh` script handles the formatting better than the other (more simpler) method?

Thanks

**Comment by eth-p** [comment]
It mainly just adds tiny quality of life conveniences (e.g. `--pager` is forwarded to `bat`) and safer variable expansion when the path to the `bat` executable contains special characters.

The manpage text is still highlighted entirely by `bat`, and would be the same no matter which method you use.
