### ISSUE TITLE
Invalid symlink

### ISSUE THREAD

**Issue by odedlaz** [eth-p/bat-extras#6]
The following line doesn't work when `batman.sh` is symlinked.

https://github.com/eth-p/bat-extras/blob/358632ed9d0d108b6c3fc8e2397640dda82db4ce/src/batman.sh#L8

If we change the former to:
```shell
LIB="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/../lib"
```
`LIB` will be set to the "real" `src` directory.

Do you want me to open a PR?

**Comment by eth-p** [comment]
Good catch. Is there a portable way to do this without using python or another scripting language?

**MacOS:**
`readlink -f` --> `readlink: illegal option -- f`
`realpath` --> `realpath: command not found`

**Comment by jgspratt** [comment]
I can confirm that it **doesn't** work on a mac.

This, however, does:

```
THIS_PATH=$(realpath $0)
THIS_DIR=$(dirname ${THIS_PATH})
THIS_PARENT_DIR=$(dirname ${THIS_DIR})
LIB="$THIS_PARENT_DIR/lib"
```

**Comment by eth-p** [comment]
Uh oh. Maybe my `readlink` command was installed by a homebrew package and I didn't realize it...

I'm hoping to avoid using more than one line (the build script only replaces `LIB=`), but I'll see what I can do to adapt your solution!

**Comment by jgspratt** [comment]
Awesome.

My solution was verbose just to make it readable. Turning it into a single, nested line should work fine.

**Comment by eth-p** [comment]
I reset my PATH to `/usr/bin:/bin:/usr/sbin:/sbin` and tried your solution, and it unfortunately didn't work.

```
batgrep.sh: line 10: realpath: command not found
usage: dirname path
usage: dirname path
batgrep.sh: line 15: /lib/print.sh: No such file or directory
batgrep.sh: line 16: /lib/pager.sh: No such file or directory
batgrep.sh: line 17: /lib/opt.sh: No such file or directory
batgrep.sh: line 18: /lib/opt_hooks.sh: No such file or directory
batgrep.sh: line 19: /lib/version.sh: No such file or directory
batgrep.sh: line 23: hook_color: command not found
batgrep.sh: line 24: hook_pager: command not found
batgrep.sh: line 41: bat_version: command not found
batgrep.sh: line 41: version_compare: command not found
batgrep.sh: line 46: shiftopt: command not found
batgrep.sh: line 115: print_error: command not found
```

**Comment by jgspratt** [comment]
This is `10.14.6`

MacOS:

```
$ which realpath
/usr/local/bin/realpath
```

AWS Linux:

```
$ which realpath
/usr/bin/realpath
```

**Comment by eth-p** [comment]
We appear to be running the same version of MacOS. Here's what I got:

```
bash-5.0$ echo "$PATH"
/Users/eth-p/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/eth-p/.bin:/usr/local/Cellar/perl/5.30.1/bin

bash-5.0$ which realpath
/usr/local/bin/realpath

bash-5.0$ realpath "$(which realpath)"
/usr/local/Cellar/coreutils/8.31/bin/grealpath

bash-5.0$ tr ':' $'\n' <<< "$PATH" | xargs -I {} find {} -name "realpath"
/usr/local/bin/realpath
```

Unfortunately, that suggests that the the version of `realpath` located at `/usr/local/bin` was installed by the homebrew `coreutils` package. I could always make it a requirement to install `coreutils` and use the Linux-friendly solution, but I'm hoping to avoid install dependencies.

**Comment by jgspratt** [comment]
Good point.

I'd lean towards the `coreutils`, (if you want `bat`, you're probably running homebrew and coreutils already, but I can understand wanting to be completely dependency free.

How about [this](https://stackoverflow.com/a/3572105/7960716)?

**Comment by eth-p** [comment]
> How about this?

That doesn't resolve symlinks, unfortunately.

---

I did a bit of testing today to see if I could come up with resolution, but I can't seem to reproduce the issue for the expected configuration (one symlink from `/usr/local/bin` to the file in `src/`) anymore. I'm not sure if I'm doing it correctly, but I tried the following:

```bash
$ cd /usr/local/bin
$ ln -s ~/Projects/bat-extras/batman.sh batman
$ ls -la . | grep batman
lrwxr-xr-x    1 eth-p  admin     57 18 Jan 15:57 batman -> /Users/eth-p/Projects/github.com/bat-extras/src/batman.sh

$ batman test
-- expected output --

$ ./batman test
-- expected output --
```

I can imagine it wouldn't work if I have a symlink pointing to another symlink (and it doesn't), but I don't feel like that's a common enough scenario to warrant requiring the `coreutils` dependency.

```bash
$ cd /usr/local/bin
$ ln -s batman batman2
$ ./batman2
./batman2: line 10: /usr/local/bin/../lib/pager.sh: No such file or directory
./batman2: line 11: /usr/local/bin/../lib/print.sh: No such file or directory
./batman2: line 12: /usr/local/bin/../lib/opt.sh: No such file or directory
./batman2: line 13: /usr/local/bin/../lib/opt_hooks.sh: No such file or directory
./batman2: line 15: hook_color: command not found
./batman2: line 16: hook_pager: command not found
./batman2: line 21: shiftopt: command not found
./batman2: line 22: : command not found
What manual page do you want?
```

**Comment by jgspratt** [comment]
If I comment out my solution and replace it with the one from the PR you opened, I get this:

```
# batman ls
/Users/justin/bin/batman: line 13: cd: bat-extras/src: No such file or directory
/Users/justin/bin/batman: line 16: /../lib/pager.sh: No such file or directory
/Users/justin/bin/batman: line 17: /../lib/print.sh: No such file or directory
/Users/justin/bin/batman: line 18: /../lib/opt.sh: No such file or directory
/Users/justin/bin/batman: line 19: /../lib/opt_hooks.sh: No such file or directory
/Users/justin/bin/batman: line 21: hook_color: command not found
/Users/justin/bin/batman: line 22: hook_pager: command not found
/Users/justin/bin/batman: line 27: shiftopt: command not found
/Users/justin/bin/batman: line 28: : command not found
What manual page do you want?
```

```
# cat ~/bin/bat-extras/src/batman.sh
#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# bat-extras | Copyright (C) 2019 eth-p | MIT License
#
# Repository: https://github.com/eth-p/bat-extras
# Issues:     https://github.com/eth-p/bat-extras/issues
# -----------------------------------------------------------------------------
#THIS_PATH=$(realpath $0)
#THIS_DIR=$(dirname ${THIS_PATH})
#THIS_PARENT_DIR=$(dirname ${THIS_DIR})
#LIB="$THIS_PARENT_DIR/lib"

LIB="$(cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo "${BASH_SOURCE[0]}")")" && pwd)/../lib"
...
```

**Comment by eth-p** [comment]
Thanks! This line here appears to be the issue we're facing:

```
/Users/justin/bin/batman: line 13: cd: bat-extras/src: No such file or directory
```

It's failing to cd into the src directory. I'll replicate your setup and see what I can do about it. In the worst case, I'll just have to make `coreutils` a soft dependency.

**Comment by eth-p** [comment]
I attempted a fix for relative symlinks and added a test to prevent regressions. Let me know if it works for you!

**Comment by jgspratt** [comment]
Confirmed working on mac.  Brilliant.

One question while I have you: in regular `man`, when I exit the man page (`q`), I return to my shell with nothing shown except the previous command (no actual `man` page content).

When I use `batman` instead, I get whatever I was looking at left over on my screen and the prompt (so one full page is used up).

`htop` says that my `less` command is this:

```
less --RAW-CONTROL-CHARS --no-init --quit-if-one-screen
```

When I run just `man ls` I get this:

```
/usr/bin/less -is
```

Is this setting controllable?  Could I control it for just `batman` and not `bat`?

**Comment by eth-p** [comment]
Great to hear that it's working!

As far as the pager goes, it's designed to mimic the way bat handles paging. I might be able to add an override that makes it consider `MANPAGER` over `BAT_PAGER` for the batman script, if you want to open a new issue for it. That would let you set `export MANPAGER=less -is --RAW-CONTROL-CHARS`.

An easy alternative could be to use a wrapper script that sets the `BAT_PAGER` variable before running the script, though.
