### ISSUE TITLE
batpipe doesn't seem to work correctly

### ISSUE THREAD

**Issue by xenoterracide** [eth-p/bat-extras#61]
```
❯ env | grep -i 'bat\|less'                                                 # ~
PAGER=less --chop-long-lines
LESS=-R --quit-if-one-screen --silent -R
MANPAGER=sh -c 'col -bx | bat -l man -p'
LESSOPEN=|/usr/bin/batpipe %s
BATPIPE=color
❯ less ~/Downloads/ideaIU-2021.1.2.tar.gz                                   # ~
───────┬────────────────────────────────────────────────────────────────────────
       │ File: /home/xeno/Downloads/ideaIU-2021.1.2.tar.gz   <BINARY>
───────┴────────────────────────────────────────────────────────────────────────
❯  
```

if I call `batpipe ~/Downloads/ideaIU-2021.1.2.tar.gz` I get a tar listing, no real highlighting though. I haven't been able to figure out how to list one file. the `:` syntax of `lessopen` doesn't seem to work.

```
bat-extras-git                                                                                                                 [Installed] 2021.04.06.r7.g20cdf5a-1  AUR 
```

**Comment by eth-p** [comment]
> ``` 
> less ~/Downloads/ideaIU-2021.1.2.tar.gz                                   # ~
> ───────┬────────────────────────────────────────────────────────────────────────
>        │ File: /home/xeno/Downloads/ideaIU-2021.1.2.tar.gz   <BINARY>
> ───────┴────────────────────────────────────────────────────────────────────────

That's odd... that should show a listing. What operating system and distro are you running?

> I haven't been able to figure out how to list one file. the `:` syntax of `lessopen` doesn't seem to work.

Use `/` instead of `:` :)

`$ less ~/Downloads/bat-extras-2021.04.06.tar.gz`

![image](https://user-images.githubusercontent.com/32112321/130337039-7696ce88-6b5d-47ba-ac70-f8955ec1df4b.png)

**Comment by xenoterracide** [comment]
I had a problem a few weeks back, part of my OS was hosed, but it wasn't obvious. I'm going to assume this is part of that, as I'm not reproducing atm.
