### ISSUE TITLE
batman: same behavior as man after close

### ISSUE THREAD

**Issue by nazrhyn** [eth-p/bat-extras#7]
Is there some way to configure `batman` to act the same as `man` (and `less`, I guess) after closing? Here's a screen recording to show what I mean:

![Peek 2019-12-03 13-23](https://user-images.githubusercontent.com/1672405/70078586-f4a42380-15d0-11ea-83b6-4b8df446b981.gif)

After closing, `man` sort of cleans up after itself so the terminal just goes back to the way it was before.

**Comment by eth-p** [comment]
Good catch. In https://github.com/eth-p/bat-extras/commit/e967497387f9a74bdcf45118d2d5a2f7b42910f9, I just fixed the `batman` script to follow the pager behaviour of the other scripts.

As long as you have your `BAT_PAGER` environment variable unset or set to `less -R`, it should work like `man` does.

**Comment by nazrhyn** [comment]
Awesome! I'll check this out and confirm either tomorrow or after the holidays. Thanks for the response!

**Comment by eth-p** [comment]
Just a small detail that I forgot to mention earlier:

If you want it to work like `man` when neither `PAGER` nor `BAT_PAGER` are set, you'll need to use a build of `bat` with https://github.com/sharkdp/bat/pull/786 merged into it. There aren't any release builds with it at the moment, though.

It would likely be easier to set `BAT_PAGER='less -R'`.

**Comment by nazrhyn** [comment]
I can totally throw that into my profile script. Thanks for the heads up.

**Comment by nazrhyn** [comment]
Confirmed that this works! Thanks for the quick fix and happy new year!

**Comment by eth-p** [comment]
Thanks for the confirmation, and happy new year!
