### ISSUE TITLE
Set default printer for `batdiff`

### ISSUE THREAD

**Issue by ChocolateOverflow** [eth-p/bat-extras#77]
I'd like to be able to set `delta` as the default printer for `batdiff` instead of `bat`. I currently use `alias batdiff="batdiff --delta"` but I prefer configuration via a config file or environmental variable, making it easier to configure the script for my whole user space without having to specify `--delta` in my scripts and shell configs.

**Comment by eth-p** [comment]
I was about to implement this, and then I realized that I actually implemented with the initial version of the script but didn't document it anywhere. I am happy to say that [it is now documented](https://github.com/eth-p/bat-extras/blob/master/doc/batdiff.md#environment).
