### ISSUE TITLE
How do I set `MANPAGER` to batman?

### ISSUE THREAD

**Issue by peterlobster** [eth-p/bat-extras#78]
For some reason, when I try to set `MANPAGER` to batman (on my Gentoo) it doesn't work. When I use the method on `bat`, it does work but I think it doesn't like it. 

Here's what I get when I set `MANPAGER` to `batman`

```shell
$ printenv | grep MANPAGER
MANPAGER=batman
```

```shell
$ man man
```
Result:
![image](https://user-images.githubusercontent.com/38382145/183470346-5ba7c2c8-067c-4d81-89c5-540de37b5989.png)

```shell
$ batman man
```

Result:
![image](https://user-images.githubusercontent.com/38382145/183470511-65a4caca-6d52-4274-902a-df045dfae521.png)

**Comment by tcoliver** [comment]
Not sure if this is the intended method, but you can

`alias man='batman'`

Then just use man like normal.

**Comment by eth-p** [comment]
Sorry for the late response. @tcoliver is correct, that's the intended method :)

**Comment by eth-p** [comment]
Clarified the documentation surrounding this in c9e917e.
