### ISSUE TITLE
batgrep: support -S/--smart-case

### ISSUE THREAD

**Issue by kergoth** [eth-p/bat-extras#8]
As the subject states, I'd love to be able to use -S with batgrep, or better yet, support an env var or argument to pass through arbitrary additional args with the caveat that it mustn't change the output formatting.

**Comment by eth-p** [comment]
Fixed in https://github.com/eth-p/bat-extras/commit/a3483a658afff2de7e3800c8f47be1e0801d63b1.

**Comment by kergoth** [comment]
Thanks!
