### ISSUE TITLE
Terminal width incorrect when using `less -J`

### ISSUE THREAD

**Issue by wren** [eth-p/bat-extras#81]
Hi! I firstly wanted to thank you for this very useful project. I use it all the time and it's really streamlined my workflow in a lot of ways.

## Problem
I also wanted to report an issue when using the `-J` option in `less`. This option "Displays a status column at the left edge of the screen." I find this useful when searching in a document since it adds a `*` icon to any line with a search result. The problem that I'm having is that this makes the terminal slightly wider than bat expects, and leads to every document that is opened to be just a few characters too wide for the screen.

This issue was brought up to `bat` a while back (sharkdp/bat#376), which resulted in the addition of the `--terminal-width` option. This works great with `bat` by doing something like `bat --terminal-width=-3`. The problem when using `batpipe`, though, is that the `--terminal-width` option is overridden and not passed on to `bat` (see [here](https://github.com/eth-p/bat-extras/blob/master/src/batpipe.sh#L322)).

I'm not sure why this behavior exists in `batpipe`, but I assume there's a reason. I was wondering if this could be updated to account for the `--terminal-width` option somehow and pass it on to `bat` when present.

## Proposed Solution
I was thinking that an environment variable (e.g. `BATPIPE_TERM_WIDTH` or whatever) could be introduced to adjust the term width. When present, it would adjust the number passed to `--terminal-width`.

If there's a different preferred approach, though, just let me know. Either way, I'm happy to send a PR to fix this once I hear if this fix would be welcome.

Thank you!

**Comment by eth-p** [comment]
Thanks for the suggestion! I originally created this project for my own workflow-related reasons, and it's always nice to hear that it's helped others too :)

I implemented your suggestion in 4e2bd77de91f57865ed00a95d7dcd8e0910107b5. I tested it locally with `less -J` and it seemed to work as intended, but please let me know if you encounter any issues with it. A new release should be coming soon-ish, after I've read through all the issues and PRs that I've been behind on.
