### ISSUE TITLE
Build option to specify dependency executable name/path

### ISSUE THREAD

**Issue by gabokamaze** [eth-p/bat-extras#92]
Hi,
To begin, thank you for this nice tool.

In the same manner than `--alternate-executable`, could it be possible to add new argument to the build.sh script in order to specify path to dependencies. I am thinking for example about `ripgrep`, but maybe also for other tool(s) that is eventually used by bat-extras and I do not know their existence.

To be clear : I have `ripgrep` installed in a non-standard folder, and I do not want to add this folder to any $PATH env variable (I have an alias `rg` pointing toward the executable) -> is there a workaround for this kind of usage ?

If no workaround, could it be possible to add something like `--ripgrep-executable` or make `--alternate-executable` be able to manage comma separated list to specify `bat`, `ripgrep`, ... executable paths ?

Thanks by advance for your response.
Regards

**Comment by eth-p** [comment]
> To be clear : I have ripgrep installed in a non-standard folder, and I do not want to add this folder to any $PATH env variable (I have an alias rg pointing toward the executable) -> is there a workaround for this kind of usage ?

There is now! Implemented as of https://github.com/eth-p/bat-extras/commit/7107e1603fab22c654ae2f5a16065d002a2b10e2:

```bash
./build.sh --alternate-executable:ripgrep "/my/path/to/rg"
```
